### ISSUE TITLE
screwbreaker  OpenC64MegaDrivePadAdapter V6 broke compatibility with some C64 games

### ISSUE THREAD

**Issue by lolof70** [SukkoPera/OpenC64MegaDrivePadAdapter#3]
Hi,

I just built the screwbreaker's V6 one.
I do not know if it's the right place to speak about  this version. I did not find a place to do it on screwbreake's github.

V6 broke compatibility on C64 side for some games... 
For exemple, it's not working with Wonderboy, giana sister and lot of other games....

It seems V5 was working well....
It‘s working perfectly on Amiga….

Could someone help me to solve this.

Thank you in advance.

**Comment by screwbreaker** [comment]
Hi,

To be honest I didn't tested the V6 on the C64 at all. The changes over the
V5 was so small, that i didn't thought it can cause any issue.
I'll check it ASAP.

Thanks for the feedback.

Il giorno ven 5 ago 2022 alle ore 18:48 lolof70 ***@***.***>
ha scritto:

**Comment by rainisto** [comment]
On my tests it seems that V6's R5 causes ghost left/right triggers on Joyport1, when replaced R5 resistor with a direct wire (which makes it match V5 schematic) then then ghost events disappeared on C64 Joyport1. You might want to try putting jumper wire to R5 and see if it fixes it lolof70.

**Comment by SukkoPera** [comment]
May I ask why this has not been opened on [screwbreaker's fork](https://github.com/screwbreaker/OpenC64MegaDrivePadAdapter)?

Please open a new Issue there and go on with the discussion.

**Comment by screwbreaker** [comment]
My bad. Issues was not active on my github page. Now they are. The issue can be opened in the repo page. 
And, I'm working on a fix. Well, I already made a new revision. I need to do some prototype.
